//
// Created by wpsimon09 on 28/04/24.
//

#ifndef PABLO_RENDERER_LIGHTTYPES_H
#define PABLO_RENDERER_LIGHTTYPES_H

enum LIGHT_TYPE{
    DIRECTIONAL = 0,
    POINT = 1,
    AREA = 2
};

#endif //PABLO_RENDERER_LIGHTTYPES_H
