//
// Created by wpsimon09 on 26/06/24.
//

#ifndef MATERIALTEXTURETYPE_H
#define MATERIALTEXTURETYPE_H

enum MATERIAL_TEXTURE_TYPE {
    MATERIAL_ALBEDO = 0,
    MATERIAL_NORMAL =1,
    MATERIAL_ARM = 2,
    MATERIAL_EMMISION = 3,
    MATERIAL_AMBIENT_OCCLUSION = 4,

    UNDEFINED = -1
};

#endif //MATERIALTEXTURETYPE_H
