//
// Created by wpsimon09 on 24/03/24.
//

#ifndef PABLO_RENDERER_RENDERINGCONSTRAINS_H
#define PABLO_RENDERER_RENDERINGCONSTRAINS_H

enum RENDERING_CONSTRAINS{
    NONE = 0,
    SHADOW_ONLY = 1,
};


#endif //PABLO_RENDERER_RENDERINGCONSTRAINS_H
