name: C++ Build with OpenGL

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update package lists
        run: sudo apt-get update

      - name: Set up CMake
        run: sudo apt-get install -y cmake

      - name: Set up OpenGL dependencies
        run: |
          sudo apt-get install -y libgl1-mesa-dev libglu1-mesa-dev libxi-dev libxrandr-dev libxxf86vm-dev libxcursor-dev

      - name: Set up additional dependencies (GLFW, Assimp, Glad)
        run: |
          sudo apt-get install -y libglfw3 assimp-utils

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build

